# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  canvasbuild:
    docker:
     - image: node:8.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: rm -rf .git
      - run: npm install -g uglifycss
      - run: npm install -g uglify-js
      - run: mkdir build
      - run: cat js/*.js > build/theme.js
      - run: uglifyjs build/theme.js > build/theme.min.js
      - run: cat css/*.css > build/theme.css
      - run: uglifycss build/theme.css > build/theme.min.css
      - run: rm -rf node_modules
  pythonbuild:
    docker:
     - image: 'circleci/python:3.7.3'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: AWS Setup Environment Variables
          command: |
            echo 'export AWS_ACCESS_KEY_ID="$HSPH_CODEDEPLOY_AWS_KEY"' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY="$HSPH_CODEDEPLOY_AWS_SECRET"' >> $BASH_ENV
            source $BASH_ENV
      - aws-s3/copy:
          from: build/theme.min.css
          to: 's3://hsph-canvas'
      - aws-s3/copy:
          from: build/theme.css
          to: 's3://hsph-canvas'
      - aws-s3/copy:
          from: build/theme.js
          to: 's3://hsph-canvas'
      - aws-s3/copy:
          from: build/theme.min.js
          to: 's3://hsph-canvas'   
workflows:
  version: 2
  build-stage:
    jobs:   
      - canvasbuild:
          context: org-global
          filters:
            branches:
              only:
                - CAN-5
      - pythonbuild:
          context: org-global
          filters:
            branches:
              only:
                - CAN-5 
                
