# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  canvasbuild:
    docker:
     - image: 'circleci/python:2.7'
    steps:
      - checkout
      - run: rm -rf .git
      - run: pip install nodejs
workflows:
  version: 2
  build-stage:
    jobs:
      - canvasbuild:
          context: org-global
          filters:
            branches:
              only:
                - CAN-5
